//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tanci.BDModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chasiEntities : DbContext
    {
        public static chasiEntities _context;
        public chasiEntities()
            : base("name=chasiEntities")
        {
        }
        public static chasiEntities GetContext()
        {
            if (_context == null)
                _context = new chasiEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chasi> chasi { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Role> DiscountAmountList { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
